---
- name: Install wordpress in new server
  hosts: webservers
  become: yes
  vars_files:
    - vars/defaults.yml
    
  tasks:
  
  # update yum repo
  - name: Yum updated
    yum:
      name: '*'
      state: latest

  - name: python 3.9 installation
    yum:
      name: python39
      state: present



  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present   

  # install LAMP server
  - name: install LAMP server
    yum: name={{ item }} state=present
    loop: [ 'httpd', 'mysql-server']

  #installing php using remi-php
  - name: registering rpm key
    rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

  - name: install epel
    yum: name={{ item }} state=present
    loop: "{{ remi_packages }}"
    
 

  # update yum repo
  - name:  resetting php 
    shell: yum module reset php -y
    
 # - name:  installing php from remi php
  #  shell: yum module install php:remi-7.4 -y

  - name: Installing php from remin php
    yum: enablerepo=remi,remi-php74 name=php74 state=latest

  # install php extension
  - name: install php extensions
    yum: name={{ item }} state=present
    loop: "{{ php_modules }}"


  # start mysql service
  - name: starting mysql server
    service:
      name: mysqld
      state: started


  # mysql configuration  

  

  # seeting root password
  - name: Set the root password
    mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        name: 'root'
        password: '{{ mysql_root_password }}'
        login_unix_socket:  /var/lib/mysql/mysql.sock
        state: present
        priv: "*.*:ALL,GRANT"
        #check_implicit_admin: true

  - name: Remove all anonymous user accounts
    mysql_user:
      name: ''
      host_all: yes
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"


  - name: Remove the MySQL test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"      


  - name: Create wordpress data base
    mysql_db:
      name: "{{ mysql_db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Create user for wordpress
    mysql_user:
      name: "{{ mysql_user }}"    
      state: present
      password: "{{ mysql_password }}"
      priv: "{{ mysql_db }}.*:ALL"
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Set permissions for directories
    shell: "/usr/bin/find /var/www/html/ -type d -exec chmod 2775 {} \\;"
    

  - name: Set permissions for files
    shell: "/usr/bin/find /var/www/html/ -type f -exec chmod 0664 {} \\;"    
            
  # wordpress download and install
  - name: Wordpress download and unpacking
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "/var/www"
      remote_src: yes
  
  - name: Copy wordpress files to /html folder
    shell: cp /var/www/wordpress/. /var/www/html -r

  - name: Delete old wordpress files
    shell: rm /var/www/wordpress -r 
 
    
  - name: Set up wp-config
    template:
      src: "files/wp-config.php.j2"
      dest: "/var/www/html/wp-config.php"
        
  - name: set permissions (changing ownership)
    shell: chown -R azureuser:apache /var/www/html

  - name: set permission (chmod 774)  
    shell: chown -R azureuser:apache /var/www/html

   # apache and mysqld server started
  - name: services started   
    service: name={{ item }} state=restarted enabled=True
    loop: [ 'httpd', 'mysqld']
     

