---
- name: Install wordpress in new server
  hosts: webservers
  become: yes
  vars_files:
    - vars/default.yml
    
  tasks:
  
  # update yum repo
  - name: Yum updated
    yum:
      name: '*'
      state: latest

  # install LAMP server
  - name: install LAMP server
    yum: name={{ item }}  state=latest
    loop: [ 'httpd', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql']

   # apache server started
  - name: services started   
    service:
      name: httpd
      state: started  
     
