---
- name: Install wordpress in new server
  hosts: webservers
  become: yes
  vars_files:
    - vars/defaults.yml
    
  tasks:
  
  # update yum repo
  - name: Yum updated
    yum:
      name: '*'
      state: latest

  # install LAMP server
  - name: install LAMP server
    yum: name={{ item }} state=latest
    loop: [ 'httpd', 'mysql-server', 'php']

   # apache and mysqld server started
  - name: services started   
    service: name={{ item }} state=started  
    loop: [ 'httpd', 'mysqld']
     
